/*-------------------------------------------------------------------------------------------------------------------------
	Relocates settings for 
-------------------------------------------------------------------------------------------------------------------------*/

local PLUGIN = {}
PLUGIN.Title = "Sandbox"
PLUGIN.Description = "Sandbox settings relocated."
PLUGIN.Author = "Overv & EntranceJew"
PLUGIN.ChatCommand = nil
PLUGIN.Usage = nil
PLUGIN.Privileges = { "Sandbox Settings" }
PLUGIN.Icon = "world"
PLUGIN.Settings = {
	sbox_maxprops = {
		label = "Props",
		desc = "Max number of props.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 150,
		isconvar = true,
	},
	sbox_maxragdolls = {
		label = "Ragdolls",
		desc = "Max number of ragdolls.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 5,
		isconvar = true,
	},
	sbox_maxvehicles = {
		label = "Vehicles",
		desc = "Max number of vehicles.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 6,
		isconvar = true,
	},
	sbox_maxeffects = {
		label = "Effects",
		desc = "Max number of efects.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 50,
		isconvar = true,
	},
	sbox_maxballoons = {
		label = "Balloons",
		desc = "Max number of balloons.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 10,
		isconvar = true,
	},
	sbox_maxnpcs = {
		label = "NPCs",
		desc = "Max number of NPCs.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 10,
		isconvar = true,
	},
	sbox_maxdynamite = {
		label = "Dynamite",
		desc = "Max number of dynamite.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 10,
		isconvar = true,
	},
	sbox_maxlamps = {
		label = "Lamps",
		desc = "Max number of lamps.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 20,
		isconvar = true,
	},
	sbox_maxlights = {
		label = "Lights",
		desc = "Max number of lights.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 5,
		isconvar = true,
	},
	sbox_maxwheels = {
		label = "Wheels",
		desc = "Max number of wheels.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 20,
		isconvar = true,
	},
	sbox_maxthrusters = {
		label = "Thrusters",
		desc = "Max number of thrusters.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 30,
		isconvar = true,
	},
	sbox_maxhoverballs = {
		label = "Hoverballs",
		desc = "Max number of hoverballs.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 20,
		isconvar = true,
	},
	sbox_maxbuttons = {
		label = "Buttons",
		desc = "Max number of buttons.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 20,
		isconvar = true,
	},
	sbox_maxemitters = {
		label = "Emitters",
		desc = "Max number of emitters.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 5,
		isconvar = true,
	},
	sbox_maxspawners = {
		label = "Spawners",
		desc = "Max number of spawners.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 100,
		isconvar = true,
	},
	sbox_maxturrets = {
		label = "Turrets",
		desc = "Max number of turrets.",
		stype = "limit",
		min = 0,
		max = 200,
		default = 100,
		isconvar = true,
	},
	
	sbox_godmode = {
		label = "Godmode",
		desc = "Toggle godmode globally.",
		stype = "bool",
		default = false,
		isconvar = true,
	},
	sbox_noclip = {
		label = "Noclip",
		desc = "Toggle the ability to use noclip.",
		stype = "bool",
		default = false,
		isconvar = true,
	},
	sbox_playershurtplayers = {
		label = "PvP",
		desc = "Toggle player vs player damage.",
		stype = "bool",
		default = true,
		isconvar = true,
	},
	sbox_weapons = {
		label = "Weapons",
		desc = "Toggle the usage of weapons.\nWon't do much in DarkRP.",
		stype = "bool",
		default = true,
		isconvar = true,
	},
	g_ragdoll_maxcount = {
		label = "Keep NPC bodies",
		desc = "Toggle.",
		stype = "bool",
		default = 0,
		multiplier = 8,
		isconvar = true,
	},
	sbox_persist = {
		label = 'Persistant Mode',
		desc = "Makes everything exist ... more.",
		stype = 'bool',
		default = false,
		isconvar = true,
	},
	physgun_limited = {
		label = 'Limited Physgun',
		desc = "Less physgun to manage.",
		stype = 'bool',
		default = false,
		isconvar = true,
	},
	sbox_bonemanip_npc = {
		label = 'Bone Manipulate NPCs',
		desc = "Manipulate the bones of NPCs.",
		stype = 'bool',
		default = true,
		isconvar = true,
	},
	sbox_bonemanip_player = {
		label = 'Bone Manipulate Players',
		desc = "Manipulate the bones of players.",
		stype = 'bool',
		default = false,
		isconvar = true,
	},
	sbox_bonemanip_misc = {
		label = 'Bone Manipulate Others',
		desc = "Manipulate the bones of anything else.",
		stype = 'bool',
		default = false,
		isconvar = true,
	},
}

evolve:RegisterPlugin( PLUGIN )