/*-------------------------------------------------------------------------------------------------------------------------
	Relocates settings for 
-------------------------------------------------------------------------------------------------------------------------*/

local PLUGIN = {}
PLUGIN.Title = "Sandbox"
PLUGIN.Description = "Sandbox settings relocated."
PLUGIN.Author = "Overv & EntranceJew"
PLUGIN.ChatCommand = nil
PLUGIN.Usage = nil
PLUGIN.Privileges = { "Sandbox Settings" }
PLUGIN.Icon = "world"
PLUGIN.Settings = {
  sbox_maxprops = {
    label = "Props",
    desc = "Max number of props.",
    stype = "limit",
    value = 150,
    min = 0,
    max = 200,
    default = 150,
    isconvar = true,
  },
	sbox_maxragdolls = {
    label = "Ragdolls",
    desc = "Max number of props.",
    stype = "limit",
    value = 5,
    min = 0,
    max = 200,
    default = 5,
    isconvar = true,
  },
	sbox_maxvehicles = {
    label = "Vehicles",
    desc = "Max number of props.",
    stype = "limit",
    value = 6,
    min = 0,
    max = 200,
    default = 6,
    isconvar = true,
  },
	sbox_maxeffects = {
    label = "Effects",
    desc = "Max number of props.",
    stype = "limit",
    value = 50,
    min = 0,
    max = 200,
    default = 50,
    isconvar = true,
  },
	sbox_maxballoons = {
    label = "Balloons",
    desc = "Max number of props.",
    stype = "limit",
    value = 10,
    min = 0,
    max = 200,
    default = 10,
    isconvar = true,
  },
	sbox_maxnpcs = {
    label = "NPCs",
    desc = "Max number of props.",
    stype = "limit",
    value = 10,
    min = 0,
    max = 200,
    default = 10,
    isconvar = true,
  },
	sbox_maxdynamite = {
    label = "Dynamite",
    desc = "Max number of props.",
    stype = "limit",
    value = 10,
    min = 0,
    max = 200,
    default = 10,
    isconvar = true,
  },
	sbox_maxlamps = {
    label = "Lamps",
    desc = "Max number of props.",
    stype = "limit",
    value = 20,
    min = 0,
    max = 200,
    default = 20,
    isconvar = true,
  },
	sbox_maxlights = {
    label = "Lights",
    desc = "Max number of props.",
    stype = "limit",
    value = 5,
    min = 0,
    max = 200,
    default = 5,
    isconvar = true,
  },
	sbox_maxwheels = {
    label = "Wheels",
    desc = "Max number of props.",
    stype = "limit",
    value = 20,
    min = 0,
    max = 200,
    default = 20,
    isconvar = true,
  },
	sbox_maxthrusters = {
    label = "Thrusters",
    desc = "Max number of props.",
    stype = "limit",
    value = 30,
    min = 0,
    max = 200,
    default = 30,
    isconvar = true,
  },
	sbox_maxhoverballs = {
    label = "Hoverballs",
    desc = "Max number of props.",
    stype = "limit",
    value = 20,
    min = 0,
    max = 200,
    default = 20,
    isconvar = true,
  },
	sbox_maxbuttons = {
    label = "Buttons",
    desc = "Max number of props.",
    stype = "limit",
    value = 20,
    min = 0,
    max = 200,
    default = 20,
    isconvar = true,
  },
	sbox_maxemitters = {
    label = "Emitters",
    desc = "Max number of props.",
    stype = "limit",
    value = 5,
    min = 0,
    max = 200,
    default = 5,
    isconvar = true,
  },
	sbox_maxspawners = {
    label = "Spawners",
    desc = "Max number of props.",
    stype = "limit",
    value = 100,
    min = 0,
    max = 200,
    default = 100,
    isconvar = true,
  },
	sbox_maxturrets = {
    label = "Turrets",
    desc = "Max number of props.",
    stype = "limit",
    value = 100,
    min = 0,
    max = 200,
    default = 100,
    isconvar = true,
  },
  
  sbox_godmode = {
    label = "Godmode",
    desc = "Toggle godmode globally.",
    stype = "bool",
    value = false,
    default = false,
    isconvar = true,
  },
	sbox_noclip = {
    label = "Noclip",
    desc = "Toggle the ability to use noclip.",
    stype = "bool",
    value = false,
    default = false,
    isconvar = true,
  },
	sbox_playershurtplayers = {
    label = "PvP",
    desc = "Toggle player vs player damage.",
    stype = "bool",
    value = true,
    default = true,
    isconvar = true,
  },
	sbox_weapons = {
    label = "Weapons",
    desc = "Toggle the usage of weapons. Won't do much in DarkRP.",
    stype = "bool",
    value = true,
    default = true,
    isconvar = true,
  },
	g_ragdoll_maxcount = {
    label = "Keep NPC bodies",
    desc = "Toggle.",
    stype = "bool",
    value = 0,
    default = 0,
    multiplier = 8,
    isconvar = true,
  },
}

evolve:RegisterPlugin( PLUGIN )